[package]
name = "osgame"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
embedded-graphics = "0.8.2"
uefi = "0.36.1"

[build]
target = "x86_64-unknown-uefi"

[[bin]]
name = "osgame"
test = false
bench = false
